CLASS /sct/au5_cl_http_handler DEFINITION PUBLIC INHERITING FROM /sct/au5_cl_ui5_http_handler.

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.

ENDCLASS.

CLASS /sct/au5_cl_http_handler IMPLEMENTATION.

ENDCLASS.
