* =====================================================================
* GENERATED FILE - DO NOT EDIT (AGENTS.md rule 2)
* Source: app/webapp/manifest.json
* Embedded frontend resource, generated by tools/app2abap/trans2abap.js.
* Change the source file above and run 'npm run app2abap' to regenerate;
* the check_app2abap CI gate fails any manual edit here.
* =====================================================================
CLASS /sct/au5_cl_ui5f_manifest DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.

    CLASS-METHODS get
      RETURNING
        VALUE(result) TYPE string.

  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.


CLASS /sct/au5_cl_ui5f_manifest IMPLEMENTATION.

  METHOD get.

    result = `{` &&
             `  "_version": "1.65.0",` &&
             `  "sap.app": {` &&
             `    "id": "sctau5",` &&
             `    "type": "application",` &&
             `    "applicationVersion": {` &&
             `      "version": "0.0.1"` &&
             `    },` &&
             `    "title": "abap2UI5",` &&
             `    "description": "Create UI5 apps purely in ABAP",` &&
             `    "sourceTemplate": {` &&
             `      "id": "@sap/generator-fiori:basic",` &&
             `      "version": "1.15.0",` &&
             `      "toolsId": "3a966e20-9635-4c28-8861-d1b66f79f1de"` &&
             `    },` &&
             `    "dataSources": {` &&
             `      "http": {` &&
             `        "uri": "/sap/bc/sctau5",` &&
             `        "type": "JSON"` &&
             `      }` &&
             `    },` &&
             `    "crossNavigation": {` &&
             `      "inbounds": {` &&
             `        "sctau5-display": {` &&
             `          "semanticObject": "sctau5",` &&
             `          "action": "display",` &&
             `          "title": "",` &&
             `          "signature": {` &&
             `            "parameters": {},` &&
             `            "additionalParameters": "allowed"` &&
             `          }` &&
             `        }` &&
             `      }` &&
             `    }` &&
             `  },` &&
             `  "sap.ui": {` &&
             `    "technology": "UI5",` &&
             `    "deviceTypes": {` &&
             `      "desktop": true,` &&
             `      "tablet": true,` &&
             `      "phone": true` &&
             `    }` &&
             `  },` &&
             `  "sap.ui5": {` &&
             `    "flexEnabled": false,` &&
             `    "dependencies": {` &&
             `      "minUI5Version": "1.71.0",` &&
             `      "libs": {` &&
             `        "sap.m": {},` &&
             `        "sap.ui.core": {}` &&
             `      }` &&
             `    },` &&
             `    "contentDensities": {` &&
             `      "compact": true,` &&
             `      "cozy": true` &&
             `    },` &&
             `    "services": {` &&
             `      "ShellUIService": {` &&
             `        "factoryName": "sap.ushell.ui5service.ShellUIService",` &&
             `        "lazy": true` &&
             `      }` &&
             `    },` &&
             `    "rootView": {` &&
             `      "viewName": "sctau5.view.App",` &&
             `      "type": "XML",` &&
             `      "async": true,` &&
             `      "id": "App"` &&
             `    },` &&
             `    "resourceRoots": {` &&
             `      "sctau5_cci": "../sctau5_cci/",` &&
             `      "sctau5_ccc": "../sctau5_ccc/"` &&
             `    }` &&
             `  },` &&
             `  "sap.cloud": {` &&
             `    "public": true,` &&
             `    "service": "sctau5"` &&
             `  }` &&
             `}` &&
             `` &&
              ``.

  ENDMETHOD.

ENDCLASS.
